#!/usr/bin/python3
import json

""" The module constains a function that cintains a class base.
"""


class Base:
    """
    Class base for managing id attribute across all classes.
    Attribute:
        __nb_objects: (int): The private class attribute to count objetcts.
    Methods:
        __int__(self, id=None): Initializes base objects with a unique id.
    """
    __nb_objects = 0  # Private class attributes to count number of obects

    def __init__(self, id=None):
        """
        initialize a new instance of Base:
        Args:
            id (int, optional): If provided the instance 's id is set
            otherwise a new id is generated by ++ _nb_objects.
        """
        if id is not None:
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects

    def to_json_string(list_dictionaries):
        """Static method that returns the JSON string
        rep of list dictionaries.
        """
        if list_dictionaries is None or 0:
            return []
        else:
            return json
